# Generated by Django 3.2.9 on 2021-12-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oragnisation_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
