# Generated by Django 3.2.10 on 2022-01-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220111_0617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_beginner',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_regular',
        ),
        migrations.AddField(
            model_name='user',
            name='is_beginner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_regular',
            field=models.BooleanField(default=False),
        ),
    ]
