# Generated by Django 3.2.10 on 2022-01-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220111_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.IntegerField(default=0),
        ),
    ]
