# Generated by Django 3.2.10 on 2021-12-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211206_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='is_checkedin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
