# Generated by Django 3.2.10 on 2022-01-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
