# Generated by Django 3.2.10 on 2022-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_event_current_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='current_capacity',
            field=models.IntegerField(default=models.IntegerField(default=0)),
        ),
    ]
