# Generated by Django 3.2.10 on 2022-01-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_event_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='signup',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.signup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='current_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
