# Generated by Django 3.2.10 on 2022-02-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_event_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
