# Generated by Django 3.2.10 on 2022-02-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_event_event_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rfid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
