# Generated by Django 3.2.10 on 2022-03-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_signup_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='team',
            field=models.BooleanField(default=0),
        ),
    ]
