# Generated by Django 3.2.10 on 2022-03-03 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_signup_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='team',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
    ]
